import type { SquareTransactionsResponse } from "./types";

export const DUMMY_SQUARE_TRANSACTIONS: SquareTransactionsResponse = {
  location_name: "Samurai-tax株式会社",
  transactions: [
    {
      payment: {
        id: "RLB3SHRTY4ZVA6RCUJIH0UO3U8DZY",
        created_at: "2026-05-15T09:59:00.000Z",
        updated_at: "2026-05-15T09:59:05.000Z",
        status: "COMPLETED",
        amount_money: { amount: 15000, currency: "JPY" },
        total_money: { amount: 15000, currency: "JPY" },
        order_id: "V9KbEX2u03XH4Ff2uzNwpRJUvmbZY",
        location_id: "D7AVYMEAPJ3A3",
        receipt_number: "RLB3S",
        receipt_url: "https://squareup.com/receipt/preview/RLB3SHRTY4ZVA6RCUJIH0UO3U8DZY",
      },
      order: {
        id: "V9KbEX2u03XH4Ff2uzNwpRJUvmbZY",
        location_id: "D7AVYMEAPJ3A3",
        created_at: "2026-05-15T09:59:00.000Z",
        updated_at: "2026-05-15T09:59:00.000Z",
        state: "COMPLETED",
        version: 1,
        line_items: [
          {
            uid: "ULkg0tQTRK2bkU9fNv3IJA",
            name: "Custom Amount",
            quantity: "1",
            base_price_money: { amount: 15000, currency: "JPY" },
            gross_sales_money: { amount: 15000, currency: "JPY" },
            total_tax_money: { amount: 1363, currency: "JPY" },
            total_discount_money: { amount: 0, currency: "JPY" },
            total_money: { amount: 15000, currency: "JPY" },
            variation_total_price_money: { amount: 15000, currency: "JPY" },
            total_service_charge_money: { amount: 0, currency: "JPY" },
          },
        ],
        total_money: { amount: 15000, currency: "JPY" },
        total_tax_money: { amount: 1363, currency: "JPY" },
        total_discount_money: { amount: 0, currency: "JPY" },
        total_tip_money: { amount: 0, currency: "JPY" },
        total_service_charge_money: { amount: 0, currency: "JPY" },
        net_amounts: {
          total_money: { amount: 15000, currency: "JPY" },
          tax_money: { amount: 1363, currency: "JPY" },
          discount_money: { amount: 0, currency: "JPY" },
          tip_money: { amount: 0, currency: "JPY" },
          service_charge_money: { amount: 0, currency: "JPY" },
        },
      },
    },
    {
      payment: {
        id: "JZ9WQ4DBZ2D4XUDPSFOMURVOQJZZY",
        created_at: "2026-05-15T09:38:00.000Z",
        updated_at: "2026-05-15T09:38:05.000Z",
        status: "COMPLETED",
        amount_money: { amount: 355, currency: "JPY" },
        total_money: { amount: 355, currency: "JPY" },
        order_id: "BBI50Gi2YRzSNEsDYpKzMhwvPKRZY",
        location_id: "D7AVYMEAPJ3A3",
        receipt_number: "JZ9WQ",
        receipt_url: "https://squareup.com/receipt/preview/JZ9WQ4DBZ2D4XUDPSFOMURVOQJZZY",
      },
      order: {
        id: "BBI50Gi2YRzSNEsDYpKzMhwvPKRZY",
        location_id: "D7AVYMEAPJ3A3",
        created_at: "2026-05-15T09:38:00.000Z",
        updated_at: "2026-05-15T09:38:00.000Z",
        state: "COMPLETED",
        version: 1,
        line_items: [
          {
            uid: "mumY8Nun4BC5aKe2yyx5b",
            name: "Custom Amount",
            quantity: "1",
            base_price_money: { amount: 355, currency: "JPY" },
            gross_sales_money: { amount: 355, currency: "JPY" },
            total_tax_money: { amount: 32, currency: "JPY" },
            total_discount_money: { amount: 0, currency: "JPY" },
            total_money: { amount: 355, currency: "JPY" },
            variation_total_price_money: { amount: 355, currency: "JPY" },
            total_service_charge_money: { amount: 0, currency: "JPY" },
          },
        ],
        total_money: { amount: 355, currency: "JPY" },
        total_tax_money: { amount: 32, currency: "JPY" },
        total_discount_money: { amount: 0, currency: "JPY" },
        total_tip_money: { amount: 0, currency: "JPY" },
        total_service_charge_money: { amount: 0, currency: "JPY" },
        net_amounts: {
          total_money: { amount: 355, currency: "JPY" },
          tax_money: { amount: 32, currency: "JPY" },
          discount_money: { amount: 0, currency: "JPY" },
          tip_money: { amount: 0, currency: "JPY" },
          service_charge_money: { amount: 0, currency: "JPY" },
        },
      },
    },
    {
      payment: {
        id: "ABC123DEF456GHI789JKL012MNO345",
        created_at: "2026-05-14T14:22:00.000Z",
        updated_at: "2026-05-14T14:22:10.000Z",
        status: "COMPLETED",
        amount_money: { amount: 32780, currency: "JPY" },
        total_money: { amount: 32780, currency: "JPY" },
        order_id: "XYZ789PQR012STU345VWX678YZA901",
        location_id: "D7AVYMEAPJ3A3",
        receipt_number: "ABC12",
        receipt_url: "https://squareup.com/receipt/preview/ABC123DEF456GHI789JKL012MNO345",
      },
      order: {
        id: "XYZ789PQR012STU345VWX678YZA901",
        location_id: "D7AVYMEAPJ3A3",
        created_at: "2026-05-14T14:22:00.000Z",
        updated_at: "2026-05-14T14:22:00.000Z",
        state: "COMPLETED",
        version: 1,
        line_items: [
          {
            uid: "line1_ABC123",
            name: "シルクスカーフ",
            quantity: "2",
            base_price_money: { amount: 12000, currency: "JPY" },
            gross_sales_money: { amount: 24000, currency: "JPY" },
            total_tax_money: { amount: 2182, currency: "JPY" },
            total_discount_money: { amount: 0, currency: "JPY" },
            total_money: { amount: 24000, currency: "JPY" },
            variation_total_price_money: { amount: 24000, currency: "JPY" },
            total_service_charge_money: { amount: 0, currency: "JPY" },
          },
          {
            uid: "line2_ABC123",
            name: "レザーウォレット",
            quantity: "1",
            base_price_money: { amount: 8780, currency: "JPY" },
            gross_sales_money: { amount: 8780, currency: "JPY" },
            total_tax_money: { amount: 798, currency: "JPY" },
            total_discount_money: { amount: 0, currency: "JPY" },
            total_money: { amount: 8780, currency: "JPY" },
            variation_total_price_money: { amount: 8780, currency: "JPY" },
            total_service_charge_money: { amount: 0, currency: "JPY" },
          },
        ],
        total_money: { amount: 32780, currency: "JPY" },
        total_tax_money: { amount: 2980, currency: "JPY" },
        total_discount_money: { amount: 0, currency: "JPY" },
        total_tip_money: { amount: 0, currency: "JPY" },
        total_service_charge_money: { amount: 0, currency: "JPY" },
        net_amounts: {
          total_money: { amount: 32780, currency: "JPY" },
          tax_money: { amount: 2980, currency: "JPY" },
          discount_money: { amount: 0, currency: "JPY" },
          tip_money: { amount: 0, currency: "JPY" },
          service_charge_money: { amount: 0, currency: "JPY" },
        },
      },
    },
    {
      payment: {
        id: "FAIL99XYZ111AAA222BBB333CCC444",
        created_at: "2026-05-13T11:05:00.000Z",
        updated_at: "2026-05-13T11:05:10.000Z",
        status: "FAILED",
        amount_money: { amount: 5000, currency: "JPY" },
        total_money: { amount: 5000, currency: "JPY" },
        order_id: "FAIL00DEF111GGG222HHH333III444",
        location_id: "D7AVYMEAPJ3A3",
        receipt_number: "FAIL9",
      },
      order: {
        id: "FAIL00DEF111GGG222HHH333III444",
        location_id: "D7AVYMEAPJ3A3",
        created_at: "2026-05-13T11:05:00.000Z",
        updated_at: "2026-05-13T11:05:00.000Z",
        state: "OPEN",
        version: 1,
        line_items: [
          {
            uid: "line1_FAIL99",
            name: "抹茶セット",
            quantity: "1",
            base_price_money: { amount: 5000, currency: "JPY" },
            gross_sales_money: { amount: 5000, currency: "JPY" },
            total_tax_money: { amount: 454, currency: "JPY" },
            total_discount_money: { amount: 0, currency: "JPY" },
            total_money: { amount: 5000, currency: "JPY" },
            variation_total_price_money: { amount: 5000, currency: "JPY" },
            total_service_charge_money: { amount: 0, currency: "JPY" },
          },
        ],
        total_money: { amount: 5000, currency: "JPY" },
        total_tax_money: { amount: 454, currency: "JPY" },
        total_discount_money: { amount: 0, currency: "JPY" },
        total_tip_money: { amount: 0, currency: "JPY" },
        total_service_charge_money: { amount: 0, currency: "JPY" },
        net_amounts: {
          total_money: { amount: 5000, currency: "JPY" },
          tax_money: { amount: 454, currency: "JPY" },
          discount_money: { amount: 0, currency: "JPY" },
          tip_money: { amount: 0, currency: "JPY" },
          service_charge_money: { amount: 0, currency: "JPY" },
        },
      },
    },
  ],
};
